---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 22.12.2019 18:02
---

local sides                        = require("sides")
local json                         = require("json")
local shopconfig                   = require("shop.config")
local config                       = {}

------- helper functions
config.getItemIdentityName         = shopconfig.getItemIdentityName
config.calculateExportActivations  = shopconfig.calculateExportActivations


-- ME controller Item storage
config.address_me_storage          = "301428d7-8c8e-4c75-b0a1-6b7932b6e961"
-- ME exportbus chest
config.address_export_stack        = "3e5b6f5a-bee6-484b-9914-ead27c50f930"
config.side_export_stack           = sides.down
config.address_export_half         = "f682ef0f-2e6e-4b08-a521-35ff67538189"
config.side_export_half            = sides.south
config.address_export_single       = "c135df0b-1479-46b2-b04e-984bee845691"
config.side_export_single          = sides.east

-- Transposer Transceiver
config.address_transposer          = "29c568a4-7075-4064-b5cb-37d6ab64bbe5"
config.side_transposer_transceiver = sides.up

-- Identity configurations
config.identity_blacklist          = shopconfig.identity_blacklist
config.identity_empty              = shopconfig.identity_empty

-- Timeouts
config.timeout_export              = 60
config.crafting_timeout            = 300 -- 5 minutes, only for error message, no actions

--
config.path_logfile                = "/home/stock.log"
config.log_lines_textbox           = 500
config.max_filesize_log            = 1 * 1024 * 1024 --1 MB
config.owner                       = "kevinkk525"
config.shop_name                   = "KK's Stock Software"
config.version                     = "0.4Beta"
config.scanning_interval           = 120 -- 2 minutes
config.crafting_cpus_left          = 3
config.crafting_batch_size         = 32
config.time_sync                   = false
config.time_sync_url               = shopconfig.time_sync_url
config.time_sync_interval          = shopconfig.time_sync_interval

-- install GUI library from: pastebin run EVWjkBxg
-- OpenOS updater: pastebin run -f icKy25PF

return config