---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 05.12.2019 17:57
---

local sides  = require("sides")
local json   = require("json")
local math   = require("math")
local config = {}

------- helper functions
function config.isOwner(user)
    if type(config.owner) ~= "table" then
        return config.owner == user
    end
    for i, name in pairs(config.owner) do
        if name == user then
            return true
        end
    end
    return false
end

function config.ownerToString()
    local st = ""
    if type(config.owner) ~= "table" then
        return config.owner
    end
    for i, name in pairs(config.owner) do
        if i > 1 then
            st = st .. ", "
        end
        st = st .. name
    end
    return st
end

function config.getItemIdentityName(item, blacklist)
    -- still has problems with some IC2 items that suddenly have hasTag=false after crafting
    -- but are supposed to have hasTag=True before crafting..
    -- affected: "ic2:lapotron_crystal", "ic2:advanced_re_battery","ic2:re_battery", etc
    local name = ""
    local keys = {}
    local blk  = {}
    for key, val in pairs(config.identity_blacklist) do
        blk[key] = true
    end
    if blacklist == nil then
        blacklist = {}
    end
    for i, key in pairs(blacklist) do
        blk[key] = true
    end
    for key, value in pairs(item) do
        if key ~= "label" and key ~= "name" and key ~= "size" then
            keys[#keys + 1] = key
        end
    end
    table.sort(keys)
    table.insert(keys, 1, "label")
    table.insert(keys, 2, "name")
    for _, key in pairs(keys) do
        if blk[key] == nil then
            local it = item[key]
            if type(it) == "number" then
                it = it + .0 -- to enforce float representation on all numbers
            end
            it   = tostring(it)
            name = name .. it .. ";"
        end
    end
    return name
end

local function calculateCellsNeeded(trans)
    local cells             = 0
    local cell_slots_used   = config.maxSlots_portableCell
    local cell_items_stored = config.maxSize_portableCell
    table.sort(trans.item_pairs, function(a, b) return a.size > b.size end)
    for i, item in pairs(trans.item_pairs) do
        if item.size == config.maxSize_portableCell then
            cells = cells + 1
        else
            if cell_items_stored + item.size > config.maxSize_portableCell then
                cells             = cells + 1
                cell_slots_used   = 1
                cell_items_stored = item.size
            else
                cell_slots_used   = cell_slots_used + 1
                cell_items_stored = cell_items_stored + item.size
                if cell_slots_used >= config.maxSlots_portableCell then
                    cells             = cells + 1
                    cell_slots_used   = 0
                    cell_items_stored = 0
                end
            end
        end
    end
    if cells == 1 and cell_slots_used <= config.dropper_export_max_slots and cell_items_stored <= config.dropper_export_max_items then
        -- no cell needed
        trans.leased_cells      = 0
        trans.lease_value       = 0
        trans.transaction_value = trans.item_value
    else
        trans.leased_cells      = cells
        trans.lease_value       = cells * config.price_lease_storage_cell
        trans.transaction_value = trans.item_value + trans.lease_value
    end
end

function config.calculateExportActivations(item, size)
    local full_stack, restf = math.modf(size / item.maxSize)
    restf                   = size - (full_stack * item.maxSize)
    local half_stack, resth = math.modf(restf / (item.maxSize / 2))
    local single            = size - full_stack * item.maxSize - half_stack * (item.maxSize / 2)
    return full_stack, half_stack, single
end

function config.newTransaction()
    local trans             = {}
    trans.amount_items      = 0
    trans.item_value        = 0
    trans.lease_value       = 0
    trans.leased_cells      = 0
    trans.transaction_value = 0
    trans.item_pairs        = {}
    trans.buyer             = nil
    trans.addItem           = function(ident, item, size, price)
        local found = false
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident and item.size + size <= config.maxSize_portableCell then
                item.size  = item.size + size
                item.price = item.price + price
                found      = true
                break
            end
        end
        if not found then
            trans.item_pairs[#trans.item_pairs + 1] = { ["ident"] = ident, ["item"] = item, ["size"] = size, ["price"] = price }
        end
        trans.amount_items = trans.amount_items + size
        trans.item_value   = trans.item_value + price
        calculateCellsNeeded(trans)
    end
    trans.removeItem        = function(ident, size)
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident and item.size == size then
                trans.amount_items = trans.amount_items - size
                trans.item_value   = trans.item_value - item.price
                calculateCellsNeeded(trans)
                table.remove(trans.item_pairs, i)
                return true
            end
        end
        print("Item doesn't exist", ident, size)
        return false
    end
    trans.toJson            = function()
        local list      = {}
        local blacklist = { addItem    = true, removeItem = true, toJson = true,
                            item_pairs = true, getAmountOfItem = true }
        for key, value in pairs(trans) do
            if not blacklist[key] then
                list[key] = value
            end
        end
        list["item_pairs"] = {}
        for i, item in pairs(trans.item_pairs) do
            list.item_pairs[#list.item_pairs + 1] = { ["ident"] = item.ident, ["size"] = item.size, ["price"] = item.price }
        end
        return json.encode(list)
    end
    trans.getAmountOfItem   = function(ident)
        local amount = 0
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident then
                amount = amount + item.size
            end
        end
        return amount
    end
    return trans
end

-- ME controller Item storage
config.address_me_storage              = "ececd6ef-48ba-44c1-bff9-6190eb029ee0"
-- ME controller for ME Chest
config.address_me_chest                = "a1a24fc5-3409-4b8a-ab1c-d06ed2005723"
-- ME controller Money for money creation --> remove in next version.
config.address_me_money                = "15b52916-6f33-4fcb-89f1-ccdfd57c080b"
-- ME exportbus chest
config.address_export_stack            = "bd490ff5-16fd-4d98-b42b-1366df6e9563"
config.side_export_stack               = sides.south
config.address_export_half             = "5e25eeb1-7971-46bf-b751-8c282a4ed5db"
config.side_export_half                = sides.east
config.address_export_single           = "6f3c1ace-8043-4e80-93b9-168de1f6ea95"
config.side_export_single              = sides.north
-- ME exportbus single item
config.address_export_single_dropper   = "73995cd2-732b-4513-a0fa-4799549361f7"
config.side_export_dropper             = sides.south
-- ME exportbus portable cell
config.address_export_portable_cell    = "3de2cb69-e851-4d77-92f4-f2de794cdd92"
config.side_export_portable_cell       = sides.north

-- Redstone block vacuum chest
config.address_redstone_vacuum_chest   = "e27998b2-062e-44f2-bbdb-4f8398efd20d"
config.side_redstone_vacuum_chest      = sides.east
-- Redstone block dropper
config.address_redstone_dropper        = "3ee85d44-e174-4bcc-8b25-c1344779cf43"
config.side_redstone_dropper           = sides.west
-- Redstone block autostart
config.address_redstone_autostart      = "92dbf0a4-d6c8-4e88-a538-27ebde6f809c"

-- Transposer ME Chest export/import
config.address_transposer_me_chest     = "bb08d9a2-9871-4c7e-8aad-361d2bee09a1"
config.side_transposer_me_chest_output = sides.east
config.side_transposer_me_chest_input  = sides.up
config.side_transposer_me_chest        = sides.west
-- Transposer input
config.address_transposer_input        = "b0281ee8-91bc-4a44-be49-4e20b639bef8"
config.side_floppy                     = sides.west
config.side_dropper_input              = sides.up
config.side_vacuum_input               = sides.south
config.side_ioport_input               = sides.down

-- Transposer for system flushing (remainder of export to 4k) --> not used at the moment
--config.address_transposer_flushing     = "58ff08c5-eb2a-4f66-911e-e4d1bc35cf7d"
--config.side_chest_flushing             = sides.up
--config.side_ioport_flushing            = sides.east
--config.side_mechest_flushing           = sides.down

-- Transposer Disk Drive for input of money
config.address_transposer_drive        = "b0281ee8-91bc-4a44-be49-4e20b639bef8"
config.side_drive_transposer_eject     = sides.west -- TODO: name unclear
config.side_drive_chest_eject          = sides.up -- TODO: name unclear, trash?

-- Transposer Money Disk Drive
config.address_transposer_money_drive  = "b2950f7d-94d6-46f1-bc3f-f5fe74cabbdc"
config.side_money_drive                = sides.down
config.side_money_disk_input           = sides.up


-- Disk Drive input for money
config.address_disk_drive              = "a6aa5f69-8bcc-43dc-9c71-0813f100cdbd"

-- Disk Drive creating money
config.address_disk_drive_money        = "8566181b-a1bc-4268-be90-d19d2a19ef3e"

-- Identity configurations
config.identity_blacklist              = { ["isCraftable"] = true, ["size"] = true,
                                           ["amounts"]     = true, ["label_friendly"] = true,
                                           ["categories"]  = true, ["stock"] = true }
config.identity_empty                  = "Air;minecraft:air;0.0;false;0.0;64.0;"
config.identity_portable_cell          = "Portable Cell;appliedenergistics2:portable_cell;0.0;true;32.0;1.0;"
config.nbt_portable_cell               = {
    ["maxDamage"] = 32, ["name"] = "appliedenergistics2:portable_cell", ["damage"] = 0,
    ["label"]     = "Portable Cell", ["maxSize"] = 1, ["hasTag"] = true }
config.identity_floppy_disk            = "opencomputers:storage;1.0;true;0.0;64.0;"
config.identity_flushing_cell          = "1k ME Storage Cell;appliedenergistics2:storage_cell_1k;0.0;true;0.0;1.0;"

--
config.maxSize_portableCell            = 4032
config.maxSlots_portableCell           = 63
config.maxSlots_money_storage          = 63 * 2

-- Timeouts
config.timeout_export                  = 60
config.price_lease_storage_cell        = 50


--
config.path_file_items                 = "/home/shop/items_dirtcraft.json"
config.path_mounts                     = { "/mnt/066", "/mnt/71c", "/mnt/b0d" }
config.path_accounts                   = "/mnt/066/accounts/"
config.path_money_disks                = "/mnt/71c/money_disks.json"
config.path_logfile                    = "/mnt/b0d/shop.log"
config.path_logfile_transactions       = "/mnt/71c/transactions.log"
config.log_lines_textbox               = 500
config.max_filesize_log                = 2 * 1024 * 1024 --2 MB
config.buyer_start_money               = config.price_lease_storage_cell + 150
config.owner                           = { "kevinkk525", "MPMob", "HipjeHopje" }
config.shop_name                       = "KK's Shop"
config.version                         = "0.8Beta"
config.stock_scanning_interval         = 300 -- 5 minutes
config.dropper_export_max_slots        = 9
config.dropper_export_max_items        = 16
config.time_sync                       = false
config.time_sync_url                   = nil
config.time_sync_interval              = nil


-- Notes ingame:
-- GriefPrevention allows access to screen with:
-- /cf interact-block-secondary opencomputers:screen3 true
-- not sure about primary, didn't work with that (only) but secondary alone works:
-- /cf interact-block-primary opencomputers:screen3 true
-- shift clicking works without screen access
-- make a subclaim for these permissions with /claimsubdivide and /cuboidclaims so
-- other screens are not accessible
-- except for with shift click, so be careful with GUIs on other screens

-- install forked GUI library from: pastebin run EVWjkBxg
-- OpenOS updater: pastebin run -f icKy25PF

return config