---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 05.12.2019 17:57
---

local sides  = require("sides")
local json   = require("json")
local math   = require("math")
local config = {}

------- helper functions
function config.getItemIdentityName(item, blacklist)
    -- still has problems with some IC2 items that suddenly have hasTag=false after crafting
    -- but are supposed to have hasTag=True before crafting..
    -- affected: "ic2:lapotron_crystal", "ic2:advanced_re_battery","ic2:re_battery", etc
    local name = ""
    local keys = {}
    local blk  = {}
    for key, val in pairs(config.identity_blacklist) do
        blk[key] = true
    end
    if blacklist == nil then
        blacklist = {}
    end
    for i, key in pairs(blacklist) do
        blk[key] = true
    end
    for key, value in pairs(item) do
        if key ~= "label" and key ~= "name" and key ~= "size" then
            keys[#keys + 1] = key
        end
    end
    table.sort(keys)
    table.insert(keys, 1, "label")
    table.insert(keys, 2, "name")
    for _, key in pairs(keys) do
        if blk[key] == nil then
            local it = item[key]
            if type(it) == "number" then
                it = it + .0 -- to enforce float representation on all numbers
            end
            it   = tostring(it)
            name = name .. it .. ";"
        end
    end
    return name
end

local function calculateCellsNeeded(trans)
    local cells             = 0
    local cell_slots_used   = config.maxSlots_portableCell
    local cell_items_stored = config.maxSize_portableCell
    table.sort(trans.item_pairs, function(a, b) return a.size > b.size end)
    for i, item in pairs(trans.item_pairs) do
        if item.size == config.maxSize_portableCell then
            cells = cells + 1
        else
            if cell_items_stored + item.size > config.maxSize_portableCell then
                cells             = cells + 1
                cell_slots_used   = 1
                cell_items_stored = item.size
            else
                cell_slots_used   = cell_slots_used + 1
                cell_items_stored = cell_items_stored + item.size
                if cell_slots_used >= config.maxSlots_portableCell then
                    cells             = cells + 1
                    cell_slots_used   = 0
                    cell_items_stored = 0
                end
            end
        end
    end
    if cells == 1 and cell_slots_used <= config.dropper_export_max_slots and cell_items_stored <= config.dropper_export_max_items then
        -- no cell needed
        trans.leased_cells      = 0
        trans.lease_value       = 0
        trans.transaction_value = trans.item_value
    else
        trans.leased_cells      = cells
        trans.lease_value       = cells * config.price_lease_storage_cell
        trans.transaction_value = trans.item_value + trans.lease_value
    end
end

function config.calculateExportActivations(item, size)
    local full_stack, restf = math.modf(size / item.maxSize)
    restf                   = size - (full_stack * item.maxSize)
    local half_stack, resth = math.modf(restf / (item.maxSize / 2))
    local single            = size - full_stack * item.maxSize - half_stack * (item.maxSize / 2)
    return full_stack, half_stack, single
end

function config.newTransaction()
    local trans             = {}
    trans.amount_items      = 0
    trans.item_value        = 0
    trans.lease_value       = 0
    trans.leased_cells      = 0
    trans.transaction_value = 0
    trans.item_pairs        = {}
    trans.buyer             = nil
    trans.addItem           = function(ident, item, size, price)
        local found = false
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident and item.size + size <= config.maxSize_portableCell then
                item.size  = item.size + size
                item.price = item.price + price
                found      = true
                break
            end
        end
        if not found then
            trans.item_pairs[#trans.item_pairs + 1] = { ["ident"] = ident, ["item"] = item, ["size"] = size, ["price"] = price }
        end
        trans.amount_items = trans.amount_items + size
        trans.item_value   = trans.item_value + price
        calculateCellsNeeded(trans)
    end
    trans.removeItem        = function(ident, size)
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident and item.size == size then
                trans.amount_items = trans.amount_items - size
                trans.item_value   = trans.item_value - item.price
                calculateCellsNeeded(trans)
                table.remove(trans.item_pairs, i)
                return true
            end
        end
        print("Item doesn't exist", ident, size)
        return false
    end
    trans.toJson            = function()
        local list      = {}
        local blacklist = { addItem    = true, removeItem = true, toJson = true,
                            item_pairs = true, getAmountOfItem = true }
        for key, value in pairs(trans) do
            if not blacklist[key] then
                list[key] = value
            end
        end
        list["item_pairs"] = {}
        for i, item in pairs(trans.item_pairs) do
            list.item_pairs[#list.item_pairs + 1] = { ["ident"] = item.ident, ["size"] = item.size, ["price"] = item.price }
        end
        return json.encode(list)
    end
    trans.getAmountOfItem   = function(ident)
        local amount = 0
        for i, item in pairs(trans.item_pairs) do
            if item.ident == ident then
                amount = amount + item.size
            end
        end
        return amount
    end
    return trans
end

-- ME controller Item storage
config.address_me_storage              = "5e402454-aa2d-4163-8e16-7e0db4407b2b"
-- ME controller for ME Chest
config.address_me_chest                = "49136b22-73f8-4611-b1d3-89fe41cd6e58"
-- ME controller Money
config.address_me_money                = "d695dfd3-2b30-4e6a-b373-08d193b2d731"
-- ME exportbus chest
config.address_export_stack            = "59b377db-d97b-4ca2-93da-b5039a26d3c2"
config.side_export_stack               = sides.east
config.address_export_half             = "ee017cb2-f20e-40af-adaa-0203414c313b"
config.side_export_half                = sides.up
config.address_export_single           = "227df10c-37b0-40f2-adf2-011ff29854c9"
config.side_export_single              = sides.west
-- ME exportbus single item
config.address_export_single_dropper   = "35eb7a2d-1dd8-42a5-90b3-a32da005c988"
config.side_export_dropper             = sides.east
-- ME exportbus portable cell
config.address_export_portable_cell    = "7878447a-eb0c-4ab8-afd2-f4c6d58cbb51"
config.side_export_portable_cell       = sides.down

-- Redstone block vacuum chest
config.address_redstone_vacuum_chest   = "0fa3cbb1-1363-40ad-93db-96fe4d00779f"
config.side_redstone_vacuum_chest      = sides.north
-- Redstone block dropper
config.address_redstone_dropper        = "c0032a37-1707-48d5-ac27-785b43274c22"
config.side_redstone_dropper           = sides.down
-- Redstone block autostart
config.address_redstone_autostart      = "d00d3bfe-6751-41e4-bed8-6fc74ed57fe6"

-- Transposer ME Chest export/import
config.address_transposer_me_chest     = "eaf5a4ef-bd75-4b14-8a1e-4beb01008d9a"
config.side_transposer_me_chest_output = sides.up
config.side_transposer_me_chest_input  = sides.north
config.side_transposer_me_chest        = sides.south
-- Transposer input
config.address_transposer_input        = "311e4638-66fe-47a6-9915-7ee04176b403"
config.side_floppy                     = sides.east
config.side_dropper_input              = sides.north
config.side_vacuum_input               = sides.south
config.side_ioport_input               = sides.up

-- Transposer for system flushing (remainder of export to 4k) --> not used at the moment
--config.address_transposer_flushing     = "58ff08c5-eb2a-4f66-911e-e4d1bc35cf7d"
--config.side_chest_flushing             = sides.up
--config.side_ioport_flushing            = sides.east
--config.side_mechest_flushing           = sides.down

-- Transposer Disk Drive for input of money
config.address_transposer_drive        = "311e4638-66fe-47a6-9915-7ee04176b403"
config.side_drive_transposer_eject     = sides.east
config.side_drive_chest_eject          = sides.west

-- Transposer Money Disk Drive
config.address_transposer_money_drive  = "6c74220d-4651-4f6b-94e9-4a733e235368"
config.side_money_drive                = sides.down
config.side_money_disk_input           = sides.up


-- Disk Drive input for money
config.address_disk_drive              = "b4411191-b099-49aa-b76b-e9b8c0c67028"

-- Disk Drive creating money
config.address_disk_drive_money        = "5f1517f6-094f-434a-a567-facfb4edbce0"

-- Identity configurations
config.identity_blacklist              = { ["isCraftable"] = true, ["size"] = true,
                                           ["amounts"]     = true, ["label_friendly"] = true,
                                           ["categories"]  = true, ["stock"] = true }
config.identity_empty                  = "Air;minecraft:air;0.0;false;0.0;64.0;"
config.identity_portable_cell          = "Portable Cell;appliedenergistics2:portable_cell;0.0;true;32.0;1.0;"
config.nbt_portable_cell               = {
    ["maxDamage"] = 32, ["name"] = "appliedenergistics2:portable_cell", ["damage"] = 0,
    ["label"]     = "Portable Cell", ["maxSize"] = 1, ["hasTag"] = true }
config.identity_floppy_disk            = "opencomputers:storage;1.0;true;0.0;64.0;"
config.identity_flushing_cell          = "1k ME Storage Cell;appliedenergistics2:storage_cell_1k;0.0;true;0.0;1.0;"

--
config.maxSize_portableCell            = 4032
config.maxSlots_portableCell           = 63
config.maxSlots_money_storage          = 63 * 2

-- Timeouts
config.timeout_export                  = 60
config.price_lease_storage_cell        = 50


--
config.path_file_items                 = "/home/shop/items_dirtcraft.json"
config.path_mounts                     = { "/mnt/981", "/mnt/d39", "/mnt/f0d" }
config.path_accounts                   = "/mnt/981/accounts/"
config.path_money_disks                = "/mnt/981/money_disks.json"
config.path_logfile                    = "/mnt/d39/shop.log"
config.path_logfile_transactions       = "/mnt/f0d/transactions.log"
config.log_lines_textbox               = 500
config.max_filesize_log                = 2 * 1024 * 1024 --2 MB
config.buyer_start_money               = config.price_lease_storage_cell + 150
config.owner                           = "kevinkk525"
config.shop_name                       = "KK's Shop"
config.version                         = "0.7Beta"
config.stock_scanning_interval         = 300 -- 5 minutes
config.dropper_export_max_slots        = 9
config.dropper_export_max_items        = 16
config.time_sync_url                   = nil
config.time_sync_interval              = nil


-- Notes ingame:
-- GriefPrevention allows access to screen with:
-- /cf interact-block-secondary opencomputers:screen3 true
-- not sure about primary, didn't work with that (only) but secondary alone works:
-- /cf interact-block-primary opencomputers:screen3 true
-- shift clicking works without screen access
-- make a subclaim for these permissions with /claimsubdivide and /cuboidclaims so
-- other screens are not accessible
-- except for with shift click, so be careful with GUIs on other screens

-- install forked GUI library from: pastebin run EVWjkBxg
-- OpenOS updater: pastebin run -f icKy25PF

return config