---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 22.12.2019 18:02
---

local sides                        = require("sides")
local json                         = require("json")
local shopconfig                   = require("shop.config")
local config                       = {}

------- helper functions
config.getItemIdentityName         = shopconfig.getItemIdentityName
config.calculateExportActivations  = shopconfig.calculateExportActivations


-- ME controller Item storage
config.address_me_storage          = "066ec498-6a08-4c78-8bc3-e62c90d127a3"
-- ME exportbus chest
config.address_export_stack        = "d67057cc-3167-454c-b2cb-c5a57c11a782"
config.side_export_stack           = sides.west
config.address_export_half         = "cc5652de-0b66-4369-a93a-a17ea4ec4206"
config.side_export_half            = sides.east
config.address_export_single       = "ececf6b5-bcec-45c1-ad75-a0039172bc28"
config.side_export_single          = sides.up

-- Transposer Transceiver
config.address_transposer          = "e7babddf-5b1b-4486-aba3-a2864b9957e7"
config.side_transposer_transceiver = sides.north

-- Identity configurations
config.identity_blacklist          = shopconfig.identity_blacklist
config.identity_empty              = shopconfig.identity_empty

-- Timeouts
config.timeout_export              = 60
config.crafting_timeout            = 300 -- 5 minutes, only for error message, no actions

--
config.path_logfile                = "/home/stock.log"
config.log_lines_textbox           = 500
config.max_filesize_log            = 1 * 1024 * 1024 --1 MB
config.owner                       = "kevinkk525"
config.shop_name                   = "KK's Stock Software"
config.version                     = "0.4Beta"
config.scanning_interval           = 120 -- 2 minutes
config.crafting_cpus_left          = 3
config.crafting_batch_size         = 32
config.time_sync_url               = shopconfig.time_sync_url
config.time_sync_interval          = shopconfig.time_sync_interval

-- install GUI library from: pastebin run EVWjkBxg
-- OpenOS updater: pastebin run -f icKy25PF

return config