---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 10.12.2019 12:40
---

local thread    = require("thread")
local component = require("component")
component.gpu.setResolution(160, 50)
local gui                    = require("shop.shopGUI")
local GUI                    = require("GUI")
local computer               = require("computer")
local json                   = require("json")
local config                 = require("shop.config")
local notice                 = require("shop.gui_notice")

local workspace            = gui.workspace
local panel                  = workspace:addChild(GUI.panel(1, 2, workspace.width, workspace.height, 0xFFFFFF, 0.5))
panel.hidden                 = true

gui.menu_exit.onTouch        = function(workspace, object, e2, e3, e4, e5, e6, user)
    if user == config.owner then
        should_terminate = true
        gui.workspace:stop()
        return
    end
    gui.on_alert = true
    GUI.alert("You are not authorized to terminate this program!")
    gui.on_alert = false
end

gui.menu_money_disks.onTouch = function()
    --panel.hidden = not panel.hidden
    --workspace:draw()
    GUI.notice(workspace, 10, "Testing new alert!\nWith lots of lines\napparently", "tough so..")
    GUI.notice(workspace, 5, "Testing new alert above!\nWith lots of lines\napparently", "tough so..")
end

gui.workspace:draw(true)
gui.workspace:start()