---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 24.11.2019 21:59
---

local link  = "https://files.freiebaptisten.de/index.php/s/cLjCz36kLDJpAGr/download"
local dir   = "shop"

local shell = require("shell")
local wd    = shell.getWorkingDirectory()
shell.execute("mkdir /home/" .. dir)
shell.setWorkingDirectory("/home/" .. dir)
shell.execute("rm download")
shell.execute("mkdir /home/bin")
shell.execute("wget https://raw.githubusercontent.com/mpmxyz/ocprograms/master/home/bin/tar.lua")
shell.execute("mv tar.lua /home/bin/")
shell.execute("wget " .. link)
shell.execute("tar -x -f download") --unpacks file into current directory
shell.execute("./install.lua")
shell.execute("rm download")
shell.setWorkingDirectory(wd)