---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kevin.
--- DateTime: 16.12.2019 19:34
---
local sides       = require("sides")

local side_wakeup = sides.east
local side_output = sides.west

local component   = require("component")
local redstone    = component.redstone
local os          = require("os")

redstone.setWakeThreshold(10)

while true do
    print("loop")
    redstone.setOutput(side_output, 255)
    os.sleep(3)
    redstone.setOutput(side_output, 0)
    os.sleep(30)
end


